homeserverUrl: "https://matrix.org"
accessToken: "syt_c2l0LmxhaWZ1_EVArNpelkhjLIublJRyL_1BjjV2"

port: 33001

webhooks:
  - id: "CQUqsTv4xrGstftQTkjprJVf"
    room_ids: ["!bCweWcEIAuiedUnDss:ellietrac.ems.host"]

# Settings for controlling how logging works
# The Docker image will only consider the consoleLevel, and not write to any files.
logging:
  file: logs/matrix-bot-uptimerobot.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5
